### PR TITLE
Rep face fix

### LINKED ISSUE #46: Handling overflow of score
Score should not go negative once max int value exceeded.  How to handle?

 - Promoted?  Special code to run game faster? Requires some hidden variable related to level - faster

### LINKED ISSUE #63: Reputation is all a bit odd now
I made a bit of a booboo with the screen furniture PR but I've fixed that and it still seems to be the case that we cannot be sad anymore - we go straight from neutral to getting fired

### PR DESCRIPTION
**Pull request by ConorMcPersonal**
Draw face on the basis of difference from minReputation.  Make it a bit easier to get off SAD.

### CODE REVIEW

File: SplitFiles/customer.c [hunk 1]
```diff
@@ -159,7 +159,7 @@ void customer_func(GameComponent* customers, GameParameters* params) {
     }
 
     if (params->reputation != initialRep || 1 == g_mustRedraw) {
-        screenFace(18, 1, params->reputation, g_mustRedraw);
+        screenFace(18, 1, params->reputation - params->minReputation, g_mustRedraw);
```
Comment (ConorMcPersonal) [inline SplitFiles/customer.c:162]: This is the main change - won't get sacked from neutral face any more, but likely to go from neutral to sad between end of Day X and start of Day X+1

File: SplitFiles/face.c [hunk 2]
```diff
@@ -81,6 +81,7 @@ void screenFace(const unsigned int x, const unsigned int y, const int reputation
         happyFace(x, y);
         lastEmo = HAPPY;
     }
+    //printf(PRINTAT"%c%c""%7d", 17, 17,  reputation);
```
Comment (ConorMcPersonal) [inline SplitFiles/face.c:84]: Leave this in in case need to understand rep values during gameplay again

File: Junk/easywin.sna
Comment (ConorMcPersonal) [inline Junk/easywin.sna:1]: This is a snapshot file - should load into any spectrum emulator.  Game is playable and set to allow an easy win (display score around 160), but shows the winning message.

**Review by mcmenaminadrian — APPROVED** [review]
